- Multiserv/api/src/models/Servicios.js
> modifique el tipo de dato

- Multiserv/api/src/controller/getUsers.js
Se modifica la recuperación de datos y se devuelve más estilizado
> Se modifica la recuperación de datos y se devuelve más estilizado

- Multiserv/client/package-lock.json
Incorporo 3 carpetas al directorio Components, para complementar toda la estructura del Atomic Desing
-Molecules
-Organisms
-Templates
Agrego en cada carpeta un archivo.txt solo para que me permitiera hacer el push de los directorios
> Structure atomic client/directories

- Multiserv/client/src/Components/Atoms/Button/Button.jsx
- Multiserv/client/src/pages/Components/Components.jsx
Cambios menores en el componente button
> Button component:

- Multiserv/api/src/controller/getUsers.js
- Multiserv/api/src/controller/postUser.js
el getUserId ya funciona, agregué también los res.status de errores
> Rutas getUser y postUser(correo y password) completas

- Multiserv/api/src/controller/deleteUser.js
- Multiserv/api/src/controller/getFilter.js
- Multiserv/api/src/controller/getOrderBy.js
- Multiserv/api/src/controller/getServ.js
> Modify routes

- Multiserv/api/src/controller/postNewService.js
- Multiserv/api/src/routes/index.js
- Multiserv/api/src/routes/postNewService.js
post /newservice
por body le pasan el json
{
"category":"",
"description":"", 
"photos":["",""],
"priceRange":"",
"rating":0, 
"title":"",
"uid":"aca va el ID del USER "
}
> Ruta creada POST newService

- Multiserv/api/src/controller/postUser.js
- Multiserv/client/package-lock.json
- Multiserv/client/package.json
- Multiserv/client/src/Components/Molecules/SignInWithSocial/SignInWithSocial.jsx
- Multiserv/client/src/Components/Organisms/UserRegister/UserRegister.jsx
- Multiserv/client/src/pages/SignUp/SignUp.jsx
Se terminó el diseño del registro y se agregó autenticación con google
- Pendiente revisar registro con correo, detalle con número de teléfono
> Done signIn

- Multiserv/client/src/Components/Organisms/FormularioSignIn/FormularioSignIn.jsx
> Login funcional, google, email

- Multiserv/api/src/controller/getFilter.js
- Multiserv/api/src/controller/getOrderBy.js
- Multiserv/api/src/controller/postUser.js
- Multiserv/api/src/routes/getServices.js
> Filter services

- Multiserv/client/src/Components/Organisms/FormularioSignIn/FormularioSignIn.jsx
Mantiene la sesion abierta y cierra sesion
> Mantener sesion2

- Multiserv/client/src/Components/Organisms/FormularioSignIn/FormularioSignIn.jsx
- Multiserv/client/src/pages/Home/Home.jsx
- Multiserv/client/src/pages/SignUp/SignUp.jsx
Le hice un mini cambio al home, la foto te toma la de google si no por default la fotito del perrito
> toma la foto de la sesion

- Multiserv/client/package-lock.json
- Multiserv/client/package.json
- Multiserv/client/src/Components/Organisms/CardInformativaFormulario/CardInformativaFormulario.jsx
- Multiserv/client/src/Components/Organisms/FormularioSignIn/FormularioSignIn.jsx
-Agrego boton para regresar a la landing desde el inicio de sesion
> Agrego boton de regresar a la landing

- Multiserv/client/src/Components/Atoms/Image/Image.jsx
- Multiserv/client/src/Components/Organisms/NavBar/Nav.jsx
- Multiserv/client/src/Components/Organisms/UserProfile/UserProfile.jsx
- Multiserv/client/src/Components/Organisms/UserProfile/UserProfile.module.css
- Multiserv/client/src/pages/Home/Home.jsx
-Agrego UserProfile al Navbar
-Agrego funciones al Home
-Agrego logout en user profile
-Agrego ValidarLongitudNombre para evitar mostrar nombres que estan mal
Nota:  Falta Refactorizar
> Feat client/user profile

- Multiserv/client/src/Components/Atoms/Image/Image.jsx
- Multiserv/client/src/Components/Molecules/ServiceCard/ServiceCard.jsx
- Multiserv/client/src/pages/Home/Home.jsx
- Added icons for loading and failed image
- Modified atom for image
> Loading and failed status for images

- Multiserv/client/src/Components/Organisms/CardInformativaFormulario/CardInformativaFormulario.jsx
- Multiserv/client/src/Components/Organisms/FormularioSignIn/FormularioSignIn.jsx
Revalido los cambios del user profile
> revalidando el user profile

- Multiserv/api/src/controller/postUser.js
- Multiserv/client/package-lock.json
- Multiserv/client/src/Components/Atoms/Button/Button.jsx
- Multiserv/client/src/Components/Molecules/SignInWithSocial/SignInWithSocial.jsx
- Multiserv/client/src/Components/Organisms/CardInformativaFormulario/CardInformativaFormulario.jsx
- Multiserv/client/src/Components/Organisms/FormularioSignIn/FormularioSignIn.jsx
- Multiserv/client/src/pages/Home/Home.jsx
- Multiserv/client/src/pages/SignUp/SignUp.jsx
-Home:
--Add 'cursor-pointer' class to user pic
-Sign_In:
--Added button for return to signUp
--Fixed bug on signInWithSocial component
-Sign_up:
--Solved bug that caused crashing on /home
--Saving user data in localStorage
-Backend (POST /agregar-usuario):
--refactor to return all user data instead of uid
> refactor_bugFix(client/SignIn_signUp):

- Multiserv/client/src/Components/Molecules/Select/Select.jsx
- Multiserv/client/src/pages/Home/Home.jsx
- Multiserv/client/src/redux/actionTypes/actionTypes.js
- Multiserv/client/src/redux/actions/actions.js
- Multiserv/client/src/redux/reducers/reducers.js
-Se agrego la barra de busqueda aun sin estilos
-Se hizo el filtrado u ordenado por rating
-Se hizo el filtrado u ordenado por alfabeto
-Surge problema ! | o situacion: si la persona quiere hacer un filtro sobre el filtro es decir un filtro de a - z sobre unos determinados servicios de la cual se hizo la busqueda, no lo podria hacer ya que el filtrado se hizo directamente desde el backend
> Añadiendo la barra de busqueda 

- Multiserv/api/src/controller/postUser.js
- Multiserv/client/src/Components/HeadLess/ListBox/ListBox.jsx
- Multiserv/client/src/Components/Molecules/Select/Select.jsx
- Multiserv/client/src/Components/Molecules/ServiceCard/ServiceCard.jsx
- Multiserv/client/src/Components/Organisms/UserProfile/UserProfile.module.css
- Multiserv/client/src/pages/Home/Home.jsx
- Multiserv/client/src/pages/SignUp/SignUp.jsx
- Multiserv/client/src/redux/actionTypes/actionTypes.js
- Multiserv/client/src/redux/actions/actions.js
- Multiserv/client/src/redux/reducers/reducers.js
- Se dió estilos a la barra de búsqueda y filtrado en home
- Se muestran alertas de SweetAlert en errores de registro de usuarios
- Se modifica la ruta del backend POST /agregar-usuario para retornar el mensaje exacto de error
> Cambios en filtrado, y registro de usuarios:

- Multiserv/api/src/controller/postUser.js
- Multiserv/client/package-lock.json
- Multiserv/client/package.json
- Multiserv/client/src/Components/Atoms/Input/Input.jsx
- Multiserv/client/src/Components/HeadLess/ListBox/ListBox.jsx
- Multiserv/client/src/Components/Organisms/UserRegister/UserRegister.jsx
Se agregó una nueva librería (react-country-flag)
Se agregó un dropdown con banderas para seleccionar el país
Se refactorizó la ruta de postUser para que fuera opcional el número de tel
> Flags in country code:

- Multiserv/client/src/Components/Atoms/Input/Input.jsx
- Multiserv/client/src/Components/Organisms/EmailPasswordForm/EmailPasswordForm.jsx
- Se agregaron indicadores visuales en caso de error al escribir el email o las passwords
> SignUp fom:

- Multiserv/client/src/Components/Organisms/FormularioSignIn/FormularioSignIn.jsx
- Se borró funcion sin usar signInWithGoogle en el componente FormularioSignIn
- Se agregó animación de loading cuando se inicia sesión
> Se añado estado de loading al inicio de sesión

- Multiserv/client/src/App.jsx
- Multiserv/client/src/Components/Organisms/UserProfile/UserProfile.module.css
- Multiserv/client/src/pages/Home/Home.jsx
Agrego los cambios que habia hecho a main aqui e dev
> Feat client/profile user

- Multiserv/api/src/controller/postUser.js
- Multiserv/client/src/App.jsx
- Multiserv/client/src/Firebase/index.js
- Multiserv/client/src/pages/Home/Home.jsx
- Multiserv/client/src/pages/SignUp/SignUp.jsx
- Multiserv/client/src/pages/VerifyEmail/VerifyEmail.jsx
Se creó una nueva ruta /email-verification
Formulario de signUp ahora redirecciona a /email-verification en lugar de /home
se proteje la ruta /home para evitar que usuarios no verificados puedan ver el contenido
Invitados pueden seguir viendo /home
> Email verification:

- Multiserv/api/src/controller/getUsers.js
- Multiserv/api/src/routes/getUsers.js
- Multiserv/api/src/routes/index.js
Agrego ruta de get para usuarios y para usuarioId
> Ruta getUsers

- Multiserv/api/src/Funciones/User.js
- Multiserv/api/src/controller/deleteUser.js
- Multiserv/api/src/controller/getUsers.js
- Multiserv/api/src/controller/postUser.js
- Multiserv/api/src/models/Usuarios.js
- Multiserv/api/src/routes/deleteUser.js
- Multiserv/api/src/routes/getUsers.js
Se crea ruta para eliminar usuarios de la DB y de Firebase por uid
> Ruta Delete de Usuarios

- Multiserv/client/src/App.jsx
- Multiserv/client/src/Components/Organisms/FormularioSignIn/FormularioSignIn.jsx
- Multiserv/client/src/Components/Organisms/validationHandlers/EmailVerified/EmailVerified.jsx
- Multiserv/client/src/Components/Organisms/validationHandlers/EmailVerified/EmailVerified.module.css
- Multiserv/client/src/Firebase/index.js
- Multiserv/client/src/pages/Components/Components.jsx
- Multiserv/client/src/pages/UsersValidations/UsersValidations.jsx
- Multiserv/client/src/pages/VerifyEmail/VerifyEmail.jsx
- Se corrigen detalles en ruta email-validation:
> Se agrega un temporizador que deshabilita el botón de reenviar mail en 1 min
- Se agrega ruta para todos los tipos de validaciones (verificación de email, reestablecer contraseña, etc)  (/user-validations)
- Se agrega carpeta en /components/organisms/validationHandlers
> Contendrá un componente por cada tipo de validación
IMPORTANTE: En plantillas de correo en Firebase se modificó para agregar un URL de acción.
Si quieren hacer pruebas (reestablecer contraseñas y cambio de email), deberán reestablecer la URL de acción a la predeterminada.
Por ahora solamente la verificación de email está operativa con un link personalizado :)
> Email validation:

- Multiserv/client/src/pages/VerifyEmail/VerifyEmail.jsx
- Se agrega botón para salir de página de verificación de mail
> bugFix -> /email-verification:

- Multiserv/api/src/controller/postUser.js
- Multiserv/api/src/controller/putServ.js
- Multiserv/api/src/controller/putUser.js
- Multiserv/api/src/routes/editUser.js
- Multiserv/api/src/routes/index.js
Se creó la ruta PUT (http://localhost:3005/editar-usuario/:uid) 
para actualizar un usuario tanto en Firebase como en la base de datos.
> Ruta PUT para actualizar info de un usuario

- Multiserv/client/src/Components/Atoms/Input/Input.jsx
- Multiserv/client/src/Components/Organisms/FormularioSignIn/FormularioSignIn.jsx
- Multiserv/client/src/Components/Organisms/UserRegister/UserRegister.jsx
- Multiserv/client/src/Components/Organisms/validationHandlers/EmailVerified/EmailVerified.jsx
- Multiserv/client/src/Components/Organisms/validationHandlers/PasswordResetConfirm/PasswordResetConfirm.jsx
- Multiserv/client/src/Firebase/index.js
- Multiserv/client/src/pages/PasswordReset/PasswordReset.jsx
- Multiserv/client/src/pages/UsersValidations/UsersValidations.jsx
- Se creó un formulario para crear nueva contraseña
- Se creó un nuevo componente PasswordResetConfirm
- Se exportaron dos nuevas funciones en firebase/index.js (verifyPasswordResetCode y confirmPasswordReset)
> Password Reset functionality:

- Multiserv/client/src/App.jsx
- Multiserv/client/src/Components/Organisms/HomeNavigation/HomeNavigation.jsx
- Multiserv/client/src/pages/CreateService/CreateService.jsx
- Multiserv/client/src/pages/Home/Home.jsx
- Multiserv/client/src/pages/SignUp/SignUp.jsx
- Se cambió la estructura del routing en app.jsx
- Se cambió la estructura de /home, para poder renderizar el navbar en todas las rutas hijas
- Se crea HomeNavigation.jsx como navbar
- Se refactoriza Home.jsx para renderizar el contenedor de servicios
> Feature (create services)

- Multiserv/client/src/App.jsx
- Multiserv/client/src/Components/Organisms/HomeNavigation/HomeNavigation.jsx
Los componentes ya no están duplicados
> Restauración rutas

- Multiserv/api/src/controller/postCategorias.js
- Multiserv/api/src/controller/postFav.js
- Multiserv/api/src/routes/index.js
se creo el condicional si el agregado a postfav ya existe no lo agrega otra vez
> Abril arreglo de postFav

- Multiserv/api/package.json
- Multiserv/api/src/controller/resenas.js
- Multiserv/api/src/routes/resenas.js
Agrego ruta de put, delete y actualizo la ruta de post para que solo se cree una reseña por usuario
> Rutas reseñas

- Multiserv/api/index.js
- Multiserv/api/src/Funciones/User.js
Se agregaron 100 reviews a servicios random pero relacionadas a un uidClient y a un servicio existentes.
> Mockup reviews

- Multiserv/api/src/controller/putServ.js
- Multiserv/api/src/routes/putServ.js
- Multiserv/client/src/App.jsx
- Multiserv/client/src/pages/ConfirmServ/ConfirmServ.jsx
Santi listo la lógica del confirmPago, la mergeo a tu rama
> funcionalidad de confirmServ listo

- Multiserv/client/src/Components/Organisms/HomeNavigation/HomeNavigation.jsx
Cambio configuracion de modal en el home
> Feat client/panel administrador

- Multiserv/client/src/pages/CreateService/CreateService.jsx
Se agregó funcionalidad para cargar la imagen en firebase antes de continuar con el siguiente paso
> Form CreateService completo (ahora sí jajajaja)

- Multiserv/client/src/pages/CreateService/CreateService.jsx
Los cambios para subir la imagen a firebase storage
> Imagen serv

- Multiserv/client/src/pages/ControlPanel/ControlPanel.jsx
Agrego ruta protegida comentada
> agrego ruta de proteccion, comentada

- Multiserv/client/package-lock.json
- Multiserv/client/package.json
- Multiserv/client/src/App.jsx
- Multiserv/client/src/pages/DetalleServicio/DetalleServicio.jsx
-Se cambió el ícono del botón de favoritos
- Se agrega notificación toast al agregar/quitar de favoritos
> Notificación toast en favoritos

- Multiserv/client/src/pages/Home/Home.jsx
- Se corrigió el margen a los lados que mostraba la barra debido al último cambio
> Edit services

- Multiserv/api/src/Funciones/User.js
- Multiserv/api/src/controller/postServ.js
- Multiserv/api/src/models/Servicios.js
- Multiserv/client/src/Components/Molecules/ServiceCard/ServiceCard.jsx
se editaron los servicios para agregar la foto de perfil del proveedor
> profile pic visible en la card service del home

- Multiserv/client/src/pages/Home/Home.jsx
- Se agregó justify-center al contenedor de las cards de servicios
> Arreglo en contenedor de servicios

- Multiserv/client/src/pages/DetalleServicio/DetalleServicio.jsx
-agrego botón de compartir 
-dejo los iconos para compartir en un modal
-dejo visibilidad de compartir tanto para usuarios invitados, como para usuarios registrados!
> Agrego boton de compartir y estilos del modal

- Multiserv/client/src/pages/ControlPanel/ControlPanel.jsx
- Multiserv/client/src/pages/CreateService/CreateService.jsx
- Multiserv/client/src/pages/DetalleServicio/DetalleServicio.jsx
- Multiserv/client/src/pages/Profile/Profile.jsx
Botones de contacto (mail, llamada y whatsapp) en el servicio.
Corrección de ortografía.
> Contact proveedor

- Multiserv/client/src/index.css
> Fix error en index.css

- Multiserv/api/index.js
- Multiserv/api/src/controller/getHorarios.js
- Multiserv/api/src/controller/postHorarios.js
- Multiserv/api/src/controller/putHorarios.js
- Multiserv/api/src/models/Citas.js
- Multiserv/api/src/models/Horarios.js
Reverts tomasgoyret/PG-Multiserv#229
> Revert "CrarHorarios hecha"

- Multiserv/api/src/controller/postServ.js
- Multiserv/api/src/controller/putServ.js
- Multiserv/api/src/models/Servicios.js
home service en modelo de servicio
> propiedad booleana para saber si es a domicilio

- Multiserv/client/src/Components/Organisms/ReviewService/ReviewService.jsx
- Multiserv/client/src/pages/DetalleServicio/DetalleServicio.jsx
-Corrijo estilos en los cuales se mostraban bien con los detalle de servicio mockeados, pero con los que se creaban nuevos no se veian igual.
-Agrego logica a la ventana de comentarios para que solo la puedan ver las personas que estan logueadas
> Reparo conflicto de estilos en Detalle de servicio

- Multiserv/client/package-lock.json
- Multiserv/client/package.json
- Multiserv/client/src/index.css
- Multiserv/client/src/pages/CreateService/CreateService.jsx
Se actualizan los cambios de createServices
> Fix create services

- Multiserv/api/index.js
- Multiserv/api/src/controller/postCitas.js
- Multiserv/api/src/controller/postServ.js
- Multiserv/api/src/controller/putServ.js
- Multiserv/client/src/App.jsx
- Multiserv/client/src/Components/Organisms/HomeNavigation/HomeNavigation.jsx
- Multiserv/client/src/pages/AgendarCita/AgendarCita.jsx
- Multiserv/client/src/pages/CrearHorarios/CrearHorarios.jsx
- Multiserv/client/src/pages/CreateService/CreateService.jsx
- Multiserv/client/src/pages/DetalleServicio/DetalleServicio.jsx
Redireccionamiento al /home luego d crear hroarios del service en
path ---> localhost:3005/home/:idService/crear-horarios
RUTA "protegida" .... ponele.
> Componente citas

- Multiserv/client/src/Components/Molecules/PercentageReview.jsx
- Multiserv/client/src/Components/Molecules/ProgressBar/ProgressBar.jsx
- Multiserv/client/src/Components/Molecules/StarRatingReview/StarRatingReview.jsx
- Multiserv/client/src/Components/Organisms/ModalAllReviews/ModalAllReviews.jsx
- Multiserv/client/src/Components/Organisms/ReviewService/ReviewService.jsx
- Multiserv/client/src/Hooks/useReviews.js
- Multiserv/client/src/index.css
Se agrega una barra de promedio de calificaciones de reseñas de cada servicio
> Porcentaje en Reviews

- Multiserv/api/index.js
- Multiserv/api/package.json
- Multiserv/api/src/mails/mailsNotificaciones.js
- Multiserv/api/src/routes/index.js
- Multiserv/api/src/routes/mailsNotificaciones.js
- Multiserv/client/src/pages/LandingPage/LandingPage.jsx
La funcion que revisa si se acerca los turnos se ejecuta cada un minutos. Debieramos configurar para que sea un día pero por ahora queda así
> quedó configurado para envie notificaciones de turno

- Multiserv/api/src/controller/putServ.js
- Multiserv/client/src/Components/Organisms/UserProfile/UserProfile.module.css
- Multiserv/client/src/pages/CreateService/CreateService.jsx
- Multiserv/client/src/pages/EditarServicio/EditarServicio.jsx
- Se modificó el z-index del menú de usuario,
ya que se mostraban superpuestos los botones de leaflet
- Se agrega funcionalidad para editar dirección
> Editar Dirección y cambios en menú de usuarios

- Multiserv/client/src/pages/EditarServicio/EditarServicio.jsx
-Se implementó funcionalidad de detectar la ubicación automáticamente
- Se puede arrastrar el marcador de ubiación para cambiar la dirección
-Agregar/quitar disponibilidad a domicilio
> Edit address

- Multiserv/client/src/pages/EditarServicio/EditarServicio.jsx
y botón al final del componente para guardar cambios
> botón para ir a Crear horarios del servicio 

- Multiserv/client/package-lock.json
- Multiserv/client/src/App.jsx
- Multiserv/client/src/pages/ControlPanel/ControlPanel.jsx
- Multiserv/client/src/pages/NotFound404/NotFound404.jsx
> Pagina 404 Agregada

- Multiserv/api/index.js
- Multiserv/api/src/controller/postFav.js
- Multiserv/api/src/mails/mailsNotificaciones.js
- Multiserv/client/src/pages/DetalleServicio/DetalleServicio.jsx
> corazonContento

- Multiserv/api/src/Funciones/User.js
- Multiserv/client/src/pages/ControlPanel/ControlPanel.jsx
Evita que se muestren datos si no es un administrador
Fix a las reseñas duplicadas
> Panel is admin

- Multiserv/client/src/pages/CreateService/CreateService.jsx
- ahora se ven correctamente los mapas al crear servicio
> Bug mapa en el formulario de creación de servicio:

- Multiserv/client/src/pages/CrearHorarios/CrearHorarios.jsx
- Multiserv/client/src/pages/CreateService/CreateService.jsx
- Multiserv/client/tailwind.config.js
- Se arreglaron detalles en el formulario
- No puedes avanzar al paso 2 si servicio.max <= servicio.min
- Puedes arrastrar el marcador para cambiar ubicación
- Ligeras mejoras a UI / UX
> Formulario CreateServices:

- Multiserv/client/src/App.jsx
- Multiserv/client/src/Components/Organisms/CardInformativaFormulario/CardInformativaFormulario.jsx
- Multiserv/client/src/Components/Organisms/Footer/Footer.jsx
- Multiserv/client/src/Components/Organisms/FormularioSignIn/FormularioSignIn.jsx
- Multiserv/client/src/pages/DetalleServicio/DetalleServicio.jsx
- Multiserv/client/src/pages/Home/Home.jsx
- Multiserv/client/src/pages/Nosotros/Nosotros.jsx
Agrego el footer al home,
creo componente footer en organismos
agrego la propiedad target="_blank" a las etiquetas <a> que hacen redireccionamientos a redes sociales externas
> Agrego footer y corrijo redireccionamiento de las etiquetas <a> 

- Multiserv/client/src/Components/Organisms/Footer/Footer.jsx
- Multiserv/client/src/Components/Organisms/ReviewService/ReviewService.jsx
- Multiserv/client/src/pages/DetalleServicio/DetalleServicio.jsx
- Multiserv/client/src/pages/Home/Home.jsx
Hago cambios con el footer, lo quito del home y lo coloco en detalle de servicio
> Me falto algo ya lo mando

- Multiserv/client/src/pages/DetalleServicio/DetalleServicio.jsx
Se eliminan console.logs innecesarios en Detalles servicio
> debug console.log en Detalles servicio

- Multiserv/client/src/pages/CreateService/CreateService.jsx
> corrección
